### ISSUE TITLE
Some posible problems

### ISSUE THREAD

**Issue by alvaroc127** [nabeel-qlik/qlik-py-tools#2]
1. in  my  recent expirences, i executed of bat **Qlik-Py-Init**, but is possible that, do not move "generated"  and "core" folders, if you no executas the bat in the path. This problem because are statements: `move generate` and `move core`
`move generated "%~dp0\qlik-py-env"
move core `"%~dp0\qlik-py-env"`

they not have the index `%~dp0`. a possible solution is the used the comant pront opcion of file explorer:
![image](https://user-images.githubusercontent.com/18422163/40390243-2d3e1e40-5dda-11e8-96de-8b2a7b54dc24.png)

and execute the .bat the next form:

> start Qlik-Py-Init.bat

2.. the installed `pip install fbprophet`, is possible that not install. For that you can install `pip install fbprophet`, You  duty have installed ** pystan ** compiled with mingw,
i recomend that you used the next link with a guide:

http://pystan.readthedocs.io/en/latest/windows.html#

http://pystan.readthedocs.io/en/latest/windows.html#setting-up-mingw-w64-on-windows,
and 
https://facebook.github.io/prophet/docs/installation.html

**Comment by nabeel-qlik** [comment]
@alvaroc127 Thanks for bringing these to my attention. 

1. I've just updated the initialization script in the latest release (v.2.2) . I'm now using `%~dp0` for the project folders as well so that should help resolve the issue. I'm also using `xcopy` instead of `move` now, so if the initialization fails for any reason the `qlik-py-env` directory can just be deleted.

```
xcopy /E /I "%~dp0\generated" "%~dp0\qlik-py-env\generated"
xcopy /E /I "%~dp0\core" "%~dp0\qlik-py-env\core"
```

2. Yes, the `fbprophet` library does need a C++ compiler installed due to it's dependency on `pystan`. The second step in the [installation notes](https://github.com/nabeel-qlik/qlik-py-tools#installation) is on the requirement to install the Visual Studio build tools which include C++ compilers. I'll add your recommended links as well to use mingw as an alternative C++ compiler.

Cheers,
Nabeel

**Comment by nabeel-qlik** [comment]
Changes have been committed so I'm closing this issue.
